defaults:
  - base_trainer_config

name: 0_shot
configs:
  epochs: 0
  gradient_accumulation_steps: 0
  fusion_strategy: ""
  explicit_evidence: False
  common_lora_config: null
  section_lora_config: null
