defaults:
  - base_model_config

name: Meditron-7b
pipeline: ChatModelPipeline
configs:
  model_name_or_path: epfl-llm/meditron-7b
  max_seq_len: 2048
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
  pretrained_adapter_merging: null
  pretrained_adapter_paths: null
  pretrained_adapter_weights: null
