defaults:
  - base_model_config

name: MistralLite-7b
pipeline: LanguageModelPipeline
configs:
  model_name_or_path: amazon/MistralLite
  max_seq_len: 16384
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
