defaults:
  - base_model_config

name: Mistral-7b-Instruct
pipeline: ChatModelPipeline
configs:
  model_name_or_path: mistralai/Mistral-7B-Instruct-v0.1
  max_seq_len: 4096
  system_prompt: You are a clinician. Answer in 1 word whether there is a contradiction or an entailment between a section of a clinical trial report and a statement.
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
